use std::fmt::Display;

use strum::EnumIter;

use crate::resolve::inbuilt::ToStaticString;

#[derive(Copy, Clone, Eq, PartialEq, Debug, Hash, EnumIter)]
pub enum InbuiltFunction {
	Bitcast,
	All,
	Any,
	Select,
	ArrayLength,
	Abs,
	Acos,
	Acosh,
	Asin,
	Asinh,
	Atan,
	Atanh,
	Atan2,
	Ceil,
	Clamp,
	Cos,
	Cosh,
	CountLeadingZeros,
	CountOneBits,
	CountTrailingZeros,
	Cross,
	Degrees,
	Determinant,
	Distance,
	Dot,
	Exp,
	Exp2,
	ExtractBits,
	FaceForward,
	FirstLeadingBit,
	FirstTrailingBit,
	Floor,
	Fma,
	Fract,
	Frexp,
	InsertBits,
	InverseSqrt,
	Ldexp,
	Length,
	Log,
	Log2,
	Max,
	Min,
	Mix,
	Modf,
	Normalize,
	Pow,
	QuantizeToF16,
	Radians,
	Reflect,
	Refract,
	ReverseBits,
	Round,
	Saturate,
	Sign,
	Sin,
	Sinh,
	Smoothstep,
	Sqrt,
	Step,
	Tan,
	Tanh,
	Transpose,
	Trunc,
	Dpdx,
	DpdxCoarse,
	DpdxFine,
	Dpdy,
	DpdyCoarse,
	DpdyFine,
	Fwidth,
	FwidthCoarse,
	FwidthFine,
	TextureDimensions,
	TextureGather,
	TextureGatherCompare,
	TextureLoad,
	TextureNumLayers,
	TextuerNumLevels,
	TextureNumSamples,
	TextureSample,
	TextureSampleBias,
	TextureSampleCompare,
	TextureSampleCompareLevel,
	TextureSampleGrad,
	TextureSampleLevel,
	TextureSampleBaseClampToEdge,
	TextureStore,
	AtomicLoad,
	AtomicStore,
	AtomicAdd,
	AtomicSub,
	AtomicMax,
	AtomicMin,
	AtomicAnd,
	AtomicOr,
	AtomicXor,
	AtomicExchange,
	AtomicCompareExchangeWeak,
	Pack4x8Snorm,
	Pack4x8Unorm,
	Pack2x16Snorm,
	Pack2x16Unorm,
	Pack2x16Float,
	Unpack4x8Snorm,
	Unpack4x8Unorm,
	Unpack2x16Snorm,
	Unpack2x16Unorm,
	Unpack2x16Float,
	StorageBarrier,
	WorkgroupBarrier,
}

impl Display for InbuiltFunction {
	fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
		match self {
			InbuiltFunction::Bitcast => write!(f, "bitcast"),
			InbuiltFunction::All => write!(f, "all"),
			InbuiltFunction::Any => write!(f, "any"),
			InbuiltFunction::Select => write!(f, "select"),
			InbuiltFunction::ArrayLength => write!(f, "arrayLength"),
			InbuiltFunction::Abs => write!(f, "abs"),
			InbuiltFunction::Acos => write!(f, "acos"),
			InbuiltFunction::Acosh => write!(f, "acosh"),
			InbuiltFunction::Asin => write!(f, "asin"),
			InbuiltFunction::Asinh => write!(f, "asinh"),
			InbuiltFunction::Atan => write!(f, "atan"),
			InbuiltFunction::Atanh => write!(f, "atanh"),
			InbuiltFunction::Atan2 => write!(f, "atan2"),
			InbuiltFunction::Ceil => write!(f, "ceil"),
			InbuiltFunction::Clamp => write!(f, "clamp"),
			InbuiltFunction::Cos => write!(f, "cos"),
			InbuiltFunction::Cosh => write!(f, "cosh"),
			InbuiltFunction::CountLeadingZeros => write!(f, "countLeadingZeros"),
			InbuiltFunction::CountOneBits => write!(f, "countOneBits"),
			InbuiltFunction::CountTrailingZeros => write!(f, "countTrailingZeros"),
			InbuiltFunction::Cross => write!(f, "cross"),
			InbuiltFunction::Degrees => write!(f, "degrees"),
			InbuiltFunction::Determinant => write!(f, "determinant"),
			InbuiltFunction::Distance => write!(f, "distance"),
			InbuiltFunction::Dot => write!(f, "dot"),
			InbuiltFunction::Exp => write!(f, "exp"),
			InbuiltFunction::Exp2 => write!(f, "exp2"),
			InbuiltFunction::ExtractBits => write!(f, "extractBits"),
			InbuiltFunction::FaceForward => write!(f, "faceForward"),
			InbuiltFunction::FirstLeadingBit => write!(f, "firstLeadingBit"),
			InbuiltFunction::FirstTrailingBit => write!(f, "firstTrailingBit"),
			InbuiltFunction::Floor => write!(f, "floor"),
			InbuiltFunction::Fma => write!(f, "fma"),
			InbuiltFunction::Fract => write!(f, "fract"),
			InbuiltFunction::Frexp => write!(f, "frexp"),
			InbuiltFunction::InsertBits => write!(f, "insertBits"),
			InbuiltFunction::InverseSqrt => write!(f, "inverseSqrt"),
			InbuiltFunction::Ldexp => write!(f, "ldexp"),
			InbuiltFunction::Length => write!(f, "length"),
			InbuiltFunction::Log => write!(f, "log"),
			InbuiltFunction::Log2 => write!(f, "log2"),
			InbuiltFunction::Max => write!(f, "max"),
			InbuiltFunction::Min => write!(f, "min"),
			InbuiltFunction::Mix => write!(f, "mix"),
			InbuiltFunction::Modf => write!(f, "modf"),
			InbuiltFunction::Normalize => write!(f, "normalize"),
			InbuiltFunction::Pow => write!(f, "pow"),
			InbuiltFunction::QuantizeToF16 => write!(f, "quantizeToF16"),
			InbuiltFunction::Radians => write!(f, "radians"),
			InbuiltFunction::Reflect => write!(f, "reflect"),
			InbuiltFunction::Refract => write!(f, "refract"),
			InbuiltFunction::ReverseBits => write!(f, "reverseBits"),
			InbuiltFunction::Round => write!(f, "round"),
			InbuiltFunction::Saturate => write!(f, "saturate"),
			InbuiltFunction::Sign => write!(f, "sign"),
			InbuiltFunction::Sin => write!(f, "sin"),
			InbuiltFunction::Sinh => write!(f, "sinh"),
			InbuiltFunction::Smoothstep => write!(f, "smoothStep"),
			InbuiltFunction::Sqrt => write!(f, "sqrt"),
			InbuiltFunction::Step => write!(f, "step"),
			InbuiltFunction::Tan => write!(f, "tan"),
			InbuiltFunction::Tanh => write!(f, "tanh"),
			InbuiltFunction::Transpose => write!(f, "transpose"),
			InbuiltFunction::Trunc => write!(f, "trunc"),
			InbuiltFunction::TextureSample => write!(f, "textureSample"),
			InbuiltFunction::TextureSampleBias => write!(f, "textureSampleBias"),
			InbuiltFunction::TextureSampleCompare => write!(f, "textureSampleCompare"),
			InbuiltFunction::TextureSampleGrad => write!(f, "textureSampleGrad"),
			InbuiltFunction::TextureSampleLevel => write!(f, "textureSampleLevel"),
			InbuiltFunction::Dpdx => write!(f, "dpdx"),
			InbuiltFunction::DpdxCoarse => write!(f, "dpdxCoarse"),
			InbuiltFunction::DpdxFine => write!(f, "dpdxFine"),
			InbuiltFunction::Dpdy => write!(f, "dpdy"),
			InbuiltFunction::DpdyCoarse => write!(f, "dpdyCoarse"),
			InbuiltFunction::DpdyFine => write!(f, "dpdyFine"),
			InbuiltFunction::Fwidth => write!(f, "fwidth"),
			InbuiltFunction::FwidthCoarse => write!(f, "fwidthCoarse"),
			InbuiltFunction::FwidthFine => write!(f, "fwidthFine"),
			InbuiltFunction::TextureDimensions => write!(f, "textureDimensions"),
			InbuiltFunction::TextureGather => write!(f, "textureGather"),
			InbuiltFunction::TextureGatherCompare => write!(f, "textureGatherCompare"),
			InbuiltFunction::TextureLoad => write!(f, "textureLoad"),
			InbuiltFunction::TextureNumLayers => write!(f, "textureNumLayers"),
			InbuiltFunction::TextuerNumLevels => write!(f, "textureNumLevels"),
			InbuiltFunction::TextureNumSamples => write!(f, "textureNumSamples"),
			InbuiltFunction::TextureSampleCompareLevel => write!(f, "textureSampleCompareLevel"),
			InbuiltFunction::TextureSampleBaseClampToEdge => write!(f, "textureSampleBaseClampToEdge"),
			InbuiltFunction::TextureStore => write!(f, "textureStore"),
			InbuiltFunction::AtomicLoad => write!(f, "atomicLoad"),
			InbuiltFunction::AtomicStore => write!(f, "atomicStore"),
			InbuiltFunction::AtomicAdd => write!(f, "atomicAdd"),
			InbuiltFunction::AtomicSub => write!(f, "atomicSub"),
			InbuiltFunction::AtomicMax => write!(f, "atomicMax"),
			InbuiltFunction::AtomicMin => write!(f, "atomicMin"),
			InbuiltFunction::AtomicAnd => write!(f, "atomicAnd"),
			InbuiltFunction::AtomicOr => write!(f, "atomicOr"),
			InbuiltFunction::AtomicXor => write!(f, "atomicXor"),
			InbuiltFunction::AtomicExchange => write!(f, "atomicExchange"),
			InbuiltFunction::AtomicCompareExchangeWeak => write!(f, "atomic_compare_exchange_weak"),
			InbuiltFunction::Pack4x8Snorm => write!(f, "pack4x8snorm"),
			InbuiltFunction::Pack4x8Unorm => write!(f, "pack4x8unorm"),
			InbuiltFunction::Pack2x16Snorm => write!(f, "pack2x16snorm"),
			InbuiltFunction::Pack2x16Unorm => write!(f, "pack2x16unorm"),
			InbuiltFunction::Pack2x16Float => write!(f, "pack2x16float"),
			InbuiltFunction::Unpack4x8Snorm => write!(f, "unpack4x8snorm"),
			InbuiltFunction::Unpack4x8Unorm => write!(f, "unpack4x8unorm"),
			InbuiltFunction::Unpack2x16Snorm => write!(f, "unpack2x16snorm"),
			InbuiltFunction::Unpack2x16Unorm => write!(f, "unpack2x16unorm"),
			InbuiltFunction::Unpack2x16Float => write!(f, "unpack2x16float"),
			InbuiltFunction::StorageBarrier => write!(f, "storageBarrier"),
			InbuiltFunction::WorkgroupBarrier => write!(f, "workgroupBarrier"),
		}
	}
}

impl ToStaticString for InbuiltFunction {
	fn to_static_str(&self) -> &'static str {
		match self {
			InbuiltFunction::Abs => "abs",
			InbuiltFunction::Acos => "acos",
			InbuiltFunction::All => "all",
			InbuiltFunction::Any => "any",
			InbuiltFunction::Asin => "asin",
			InbuiltFunction::Atan => "atan",
			InbuiltFunction::Atan2 => "atan2",
			InbuiltFunction::Ceil => "ceil",
			InbuiltFunction::Clamp => "clamp",
			InbuiltFunction::Cos => "cos",
			InbuiltFunction::Cosh => "cosh",
			InbuiltFunction::Cross => "cross",
			InbuiltFunction::Determinant => "determinant",
			InbuiltFunction::Distance => "distance",
			InbuiltFunction::Dot => "dot",
			InbuiltFunction::Exp => "exp",
			InbuiltFunction::Exp2 => "exp2",
			InbuiltFunction::FaceForward => "faceForward",
			InbuiltFunction::Floor => "floor",
			InbuiltFunction::Fma => "fma",
			InbuiltFunction::Fract => "fract",
			InbuiltFunction::Frexp => "frexp",
			InbuiltFunction::InverseSqrt => "inverseSqrt",
			InbuiltFunction::Length => "length",
			InbuiltFunction::Log => "log",
			InbuiltFunction::Log2 => "log2",
			InbuiltFunction::Max => "max",
			InbuiltFunction::Min => "min",
			InbuiltFunction::Mix => "mix",
			InbuiltFunction::Modf => "modf",
			InbuiltFunction::Normalize => "normalize",
			InbuiltFunction::Pow => "pow",
			InbuiltFunction::QuantizeToF16 => "quantizeToF16",
			InbuiltFunction::Radians => "radians",
			InbuiltFunction::Reflect => "reflect",
			InbuiltFunction::Refract => "refract",
			InbuiltFunction::ReverseBits => "reverseBits",
			InbuiltFunction::Round => "round",
			InbuiltFunction::Saturate => "saturate",
			InbuiltFunction::Sign => "sign",
			InbuiltFunction::Sin => "sin",
			InbuiltFunction::Sinh => "sinh",
			InbuiltFunction::Smoothstep => "smoothStep",
			InbuiltFunction::Sqrt => "sqrt",
			InbuiltFunction::Step => "step",
			InbuiltFunction::Tan => "tan",
			InbuiltFunction::Tanh => "tanh",
			InbuiltFunction::Trunc => "trunc",
			InbuiltFunction::Transpose => "transpose",
			InbuiltFunction::TextureLoad => "textureLoad",
			InbuiltFunction::TextureSample => "textureSample",
			InbuiltFunction::TextureSampleBias => "textureSampleBias",
			InbuiltFunction::TextureSampleCompare => "textureSampleCompare",
			InbuiltFunction::TextureSampleGrad => "textureSampleGrad",
			InbuiltFunction::TextureSampleLevel => "textureSampleLevel",
			InbuiltFunction::TextureStore => "textureStore",
			InbuiltFunction::AtomicLoad => "atomicLoad",
			InbuiltFunction::AtomicStore => "atomicStore",
			InbuiltFunction::AtomicAdd => "atomicAdd",
			InbuiltFunction::AtomicSub => "atomicSub",
			InbuiltFunction::AtomicMax => "atomicMax",
			InbuiltFunction::AtomicMin => "atomicMin",
			InbuiltFunction::AtomicAnd => "atomicAnd",
			InbuiltFunction::AtomicOr => "atomicOr",
			InbuiltFunction::AtomicXor => "atomicXor",
			InbuiltFunction::AtomicExchange => "atomicExchange",
			InbuiltFunction::AtomicCompareExchangeWeak => "atomicCompareExchangeWeak",
			InbuiltFunction::Pack4x8Snorm => "pack4x8snorm",
			InbuiltFunction::Pack4x8Unorm => "pack4x8unorm",
			InbuiltFunction::Pack2x16Snorm => "pack2x16snorm",
			InbuiltFunction::Pack2x16Unorm => "pack2x16unorm",
			InbuiltFunction::Pack2x16Float => "pack2x16float",
			InbuiltFunction::Unpack4x8Snorm => "unpack4x8snorm",
			InbuiltFunction::Unpack4x8Unorm => "unpack4x8unorm",
			InbuiltFunction::Unpack2x16Snorm => "unpack2x16snorm",
			InbuiltFunction::Unpack2x16Unorm => "unpack2x16unorm",
			InbuiltFunction::Unpack2x16Float => "unpack2x16float",
			InbuiltFunction::StorageBarrier => "storageBarrier",
			InbuiltFunction::WorkgroupBarrier => "workgroupBarrier",
			InbuiltFunction::Bitcast => "bitcast",
			InbuiltFunction::Select => "select",
			InbuiltFunction::ArrayLength => "arrayLength",
			InbuiltFunction::Acosh => "acosh",
			InbuiltFunction::Asinh => "asinh",
			InbuiltFunction::Atanh => "atanh",
			InbuiltFunction::CountLeadingZeros => "countLeadingZeros",
			InbuiltFunction::CountOneBits => "countOneBits",
			InbuiltFunction::CountTrailingZeros => "countTrailingZeros",
			InbuiltFunction::Degrees => "degrees",
			InbuiltFunction::ExtractBits => "extractBits",
			InbuiltFunction::FirstLeadingBit => "firstLeadingBit",
			InbuiltFunction::FirstTrailingBit => "firstTrailingBit",
			InbuiltFunction::InsertBits => "insertBits",
			InbuiltFunction::Ldexp => "ldexp",
			InbuiltFunction::Dpdx => "dpdx",
			InbuiltFunction::DpdxCoarse => "dpdxCoarse",
			InbuiltFunction::DpdxFine => "dpdxFine",
			InbuiltFunction::Dpdy => "dpdy",
			InbuiltFunction::DpdyCoarse => "dpdyCoarse",
			InbuiltFunction::DpdyFine => "dpdyFine",
			InbuiltFunction::Fwidth => "fwidth",
			InbuiltFunction::FwidthCoarse => "fwidthCoarse",
			InbuiltFunction::FwidthFine => "fwidthFine",
			InbuiltFunction::TextureDimensions => "textureDimensions",
			InbuiltFunction::TextureGather => "textureGather",
			InbuiltFunction::TextureGatherCompare => "textureGatherCompare",
			InbuiltFunction::TextureNumLayers => "textureNumLayers",
			InbuiltFunction::TextuerNumLevels => "textureNumLevels",
			InbuiltFunction::TextureNumSamples => "textureNumSamples",
			InbuiltFunction::TextureSampleCompareLevel => "textureSampleCompareLevel",
			InbuiltFunction::TextureSampleBaseClampToEdge => "textureSampleBaseClampToEdge",
		}
	}
}
